run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - golint
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - unparam
    - varcheck
