language: go

os:
  - linux
  
go: 
  - "1.11.x"
  - tip

env:
  - GO111MODULE=on

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.17.1
  
script:
 - golangci-lint run ./...
 - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
