language: go

os:
  - linux
  
go: 
  - "1.11.x"
  - tip

env:
  - GO111MODULE=on

install:
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  
script:
 - ./test.sh
 - go vet ./...
 - diff <(golint ./...) <(printf "")

after_success:
  - bash <(curl -s https://codecov.io/bash)
