version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\bvwells\go-clean-arch

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d -t -v ./...

build_script:
 - go install -v ./...

test_script:
 - go test -v ./...